language: python
python:
  - "2.7"
  - "3.8"
  - "3.9"
# command to install dependencies
#install: "pip install -r requirements.txt"
# command to run tests
# Install the codecov pip dependency
install:
  - pip install codecov
script:
  - sh -c 'cd test && coverage run -m unittest discover && coverage report'
# Push the results back to codecov
after_success:
  - codecov
  - bash <(curl -s https://codecov.io/bash)